<!DOCTYPE html>
<html lang="en">
<head>
    <?php include_once 'predlosci/head.phtml' ?>
</head>
<body>
    <div class="grid-container">
        <?php include_once 'predlosci/izbornik.phtml' ?>
        <div class="callout" id="program">
            <?=$sadrzaj?>
        </div>
        <?php include_once 'predlosci/podnozje.phtml' ?>
    </div>
    <?php include_once 'predlosci/skripte.phtml' ?>
</body>
</html>